
server.port: 7002

spring:
  data:
    mongodb:
      host: localhost
      database: recommendation-db
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
    consumer:
      group-id: recommendation_group
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.eshop.recommendation.model.RecommendationEvent'

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  data.mongodb.host: mongodb
  kafka:
    bootstrap-servers: http://kafka:29092