
server.port: 7003
server.error.include-message: always

spring:

  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/review-db
    username: user
    password: pwd
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
    consumer:
      group-id: review_group
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.eshop.review.model.ReviewEvent'

logging:
  level:
    root: INFO
    com.eshop: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.config.activate.on-profile: docker

server.port: 8080
Spring:
  r2dbc:
    url: r2dbc:postgresql://postgres/review-db
  kafka:
    bootstrap-servers: http://kafka:29092